name: Bug Report
description: Raise a game-related bug report
labels: ["Bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! This template will help you with creating a report that we can use to understand the bug.

        - This repository is maintained by volunteers, it may take a while for them to come back to you.
        - Remember to include sufficient details and context.
        - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
        - We accept pull request. If you know how to fix it - go ahead!

        Please provide the following details about the issue you encountered.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the problem
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual Behaviour
      description: What is currently happening?
    validations:
      required: true

  - type: textarea
    id: problems
    attributes:
      label: Reproduction steps
      description: If you can reliably reproduce this bug, please describe how others can do so

  - type: textarea
    id: other
    attributes:
      label: Other
      description: Note any additional info here

  - type: markdown
    attributes:
      value: _This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._
